//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Castle Project")]
[assembly: AssemblyCopyright("Castle Project, original author or authors")]
[assembly: AssemblyDescription("Castle.MonoRail.ViewComponents")]
[assembly: AssemblyInformationalVersion("0.1.0.0")]
[assembly: AssemblyTitle("Castle.MonoRail.ViewComponents")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyVersion("0.1.0.0")]


